id: P001825
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-17 10:23:47.895219
source_metadata:
  id: bdr:W2CZ6645
  title: སྒ་སྟོན་ངག་དབང་ལེགས་པའི་རྣམ་ཐར་
  author: ''
  volumes:
    7708b1f7552c4e16a59f60e5c5ebef93:
      image_group_id: I1KG1603
      title: ''
      volume_number: 1
      total_pages: 94
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
