id: IAAFAEE8D
legacy_id: P001825
ocr_import_info:
  bdrc_scan_id: W2CZ6645
  source: bdrc
  ocr_info:
    timestamp: '2020-03-30T17:58:09'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T15:15:48.951984+00:00'
last_modified: 2022-09-02 23:16:08.502477
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W2CZ6645
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW2CZ6645
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སྒ་སྟོན་ངག་དབང་ལེགས་པའི་རྣམ་ཐར།
  author: ཨ་འཇམ་སྤྲུལ་སྐུ་ཀུན་དགའ་རྒྱལ་མཚན།
statistics:
  ocr_word_mean_confidence_index: 0.6961352737881796
  ocr_word_median_confidence_index: 0.8999999761581421
quality: null
bases:
  I1KG1603:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG1603
      total_pages: 94
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG1603.txt
    statistics:
      ocr_word_median_confidence_index: 0.8999999761581421
      ocr_word_mean_confidence_index: 0.6961352737881796
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
